### ISSUE TITLE
Running Django Application with superzippy

### ISSUE THREAD

**Issue by himanshu219** [brownhead/superzippy#32]
I am trying to create an executable with django application.I am not able to start my server because since it is a executable and django checks for management commands in commands dir it is throwing  following error
 OSError: [Errno 20] Not a directory: '/tmp/vkmobileexe/site-packages/django/core/management/commands'

for reference this is my main.py 

import os
import sys
def runserver():
    PROJECT_PATH = os.path.dirname(__file__)
    print PROJECT_PATH
    sys.path.append(PROJECT_PATH)
    import pdb;pdb.set_trace()    
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "vkmobile.vkmobile.settings")
    from django.core.management import execute_from_command_line
    execute_from_command_line(['manage.py', 'runserver', '8000'])

if __name__=="__main__":
    runserver()

**Comment by brownhead** [comment]
A full Django application is probably not the best fit for Superzippy. It might be possible, but I haven't tried it and I'm not sure how to move you forward with what you've sent me.

If you try [py2exe](http://www.py2exe.org/) you might have better luck. That program solves the same problem via an entirely different and more powerful method.
